#!/usr/bin/python
### Copyright (C) 2002-2006 Eli Yukelzon <reflog@gmail.com>

### This program is free software; you can redistribute it and/or modify
### it under the terms of the GNU General Public License as published by
### the Free Software Foundation; either version 2 of the License, or
### (at your option) any later version.

### This program is distributed in the hope that it will be useful,
### but WITHOUT ANY WARRANTY; without even the implied warranty of
### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
### GNU General Public License for more details.

### You should have received a copy of the GNU General Public License
### along with this program; if not, write to the Free Software
### Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


import sys
sys.path += [ #LIBDIR# ]
import paths
import gettext
import locale

version = "0.0.1"
revision = "$Id$"

try:
    locale.setlocale(locale.LC_ALL, '')
    gettext.bindtextdomain("pyterm", paths.locale_dir() )
    gettext.textdomain("pyterm")
    gettext.install("pyterm", paths.locale_dir(), unicode=1)
except (IOError,locale.Error), e:
    # fake gettext until translations in place
    print "(pyterm): WARNING **: %s" % e
    __builtins__.__dict__["_"] = lambda x : x
__builtins__.__dict__["ngettext"] = gettext.ngettext


from pte import PTE

if __name__ == "__main__":
    pte = PTE(version,#SHAREDIR#)
    pte.main(
